package com.denis.musicdataeditor.gui;

import com.denis.musicdataeditor.config.References;
import com.denis.musicdataeditor.core.Canzone;
import com.denis.musicdataeditor.image.CoverArt;
import com.denis.musicdataeditor.mxmwrapper.MXM;
import com.denis.musicdataeditor.mxmwrapper.MXMTrack;
import com.mpatric.mp3agic.ID3v2;
import com.mpatric.mp3agic.ID3v23Tag;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

public class MXMDialog extends javax.swing.JDialog {

    /**
     * Creates new form MXMDialog
     */
    public MXMDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        t_input = new javax.swing.JTextField();
        b_match = new javax.swing.JButton();
        b_prev = new javax.swing.JButton();
        b_next = new javax.swing.JButton();
        b_save = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        t_titolo = new javax.swing.JTextField();
        b_translTitle = new javax.swing.JButton();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        t_artista = new javax.swing.JTextField();
        b_transArtist = new javax.swing.JButton();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        t_album = new javax.swing.JTextField();
        b_albCover = new javax.swing.JButton();
        l_cover = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        t_anno = new javax.swing.JTextField();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        t_numero = new javax.swing.JTextField();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        cb_genere = new javax.swing.JComboBox<>();
        javax.swing.JLabel l_logoMXM = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        b_search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MXM Track Search");
        setBounds(new java.awt.Rectangle(0, 0, 52, 640));
        setMinimumSize(new java.awt.Dimension(520, 640));
        setPreferredSize(new java.awt.Dimension(520, 640));
        setSize(new java.awt.Dimension(500, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MXM Search");

        t_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        b_match.setText("Match");
        b_match.setToolTipText("mxm.matcher.track.get");
        b_match.setPreferredSize(new java.awt.Dimension(75, 23));
        b_match.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_matchActionPerformed(evt);
            }
        });

        b_prev.setText("Previous");
        b_prev.setPreferredSize(new java.awt.Dimension(75, 23));
        b_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_prevActionPerformed(evt);
            }
        });

        b_next.setText("Next");
        b_next.setPreferredSize(new java.awt.Dimension(75, 23));
        b_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_nextActionPerformed(evt);
            }
        });

        b_save.setText("Save");
        b_save.setPreferredSize(new java.awt.Dimension(75, 23));
        b_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_saveActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Title:");

        t_titolo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        b_translTitle.setText("Translation");
        b_translTitle.setMaximumSize(new java.awt.Dimension(75, 23));
        b_translTitle.setMinimumSize(new java.awt.Dimension(75, 23));
        b_translTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_translTitleActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Artist:");

        t_artista.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        b_transArtist.setText("Translation");
        b_transArtist.setMaximumSize(new java.awt.Dimension(75, 23));
        b_transArtist.setMinimumSize(new java.awt.Dimension(75, 23));
        b_transArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_transArtistActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Album:");

        t_album.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        b_albCover.setText("Cover Alb.");
        b_albCover.setMaximumSize(new java.awt.Dimension(75, 23));
        b_albCover.setMinimumSize(new java.awt.Dimension(75, 23));
        b_albCover.setPreferredSize(new java.awt.Dimension(85, 23));
        b_albCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_albCoverActionPerformed(evt);
            }
        });

        l_cover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_cover.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        l_cover.setPreferredSize(new java.awt.Dimension(350, 350));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Release Date:");
        t_anno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Genres Founs:");

        t_numero.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tack Number:");

        l_logoMXM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_logoMXM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_logoMXMMouseClicked(evt);
            }
        });
        

        jLabel10.setText("Powered By: MusixMatch");

        b_search.setText("Search");
        b_search.setToolTipText("mxm.track.search");
        b_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_cover, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_anno)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_numero)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_genere, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_logoMXM, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(t_input)
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(b_match, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_prev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t_titolo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_translTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t_artista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_transArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t_album)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_albCover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(t_input, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_match, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_prev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_titolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_translTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_transArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_albCover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_cover, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_anno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_genere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l_logoMXM, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_matchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_matchActionPerformed
        tracks = new ArrayList<>(1);
        pos = 0;
        String[] aux = References.splitArrayForInput(t_input.getText());
        tracks.add(new MXMTrack(MXM.getMatchingTrack(aux[0], aux[1])));

        guiController(tracks.get(0));

    }//GEN-LAST:event_b_matchActionPerformed

    private void b_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_prevActionPerformed
        pos--;
        if (pos < 0) pos = resultCount() - 1;
        guiController(tracks.get(pos));
    }//GEN-LAST:event_b_prevActionPerformed

    private void b_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_nextActionPerformed
        pos++;
        if (pos == resultCount()) pos = 0;
        guiController(tracks.get(pos));
    }//GEN-LAST:event_b_nextActionPerformed

    private void b_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_saveActionPerformed
        ID3v2 tags = new ID3v23Tag();
        tags.setTitle(References.toTitleCase(t_titolo.getText()));
        tags.setArtist(References.toTitleCase(t_artista.getText()));
        tags.setAlbumArtist(References.toTitleCase(t_artista.getText()));
        tags.setAlbum(References.toTitleCase(t_album.getText()));
        tags.setYear(References.toTitleCase(t_anno.getText()));
        tags.setTrack(References.toTitleCase(t_numero.getText()));
        if (!cb_genere.getSelectedItem().toString().equals("Unknown")) {
            tags.setGenreDescription((String)cb_genere.getSelectedItem());
        }
        if (l_cover.getIcon() != null) {
            tags.setAlbumImage(CoverArt.iconToByteArray(l_cover.getIcon()), "jpg");
        }
        song.setTrack_tags(tags);
        song.save();

        this.dispose();

    }//GEN-LAST:event_b_saveActionPerformed

    private void b_translTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_translTitleActionPerformed
        if (tracks == null) return;
        MXMTrack track = tracks.get(pos);
        if (track == null) return;

        if (track.getTitleTranslations() == null ||
                track.getTitleTranslations().size() == 0) // la seconda parte del if non è necessaria, ma la metto per sicurezza
        {
            JOptionPane.showMessageDialog(this, "No translated title name found.");
            return;
        }

        Object[] translations = References.normalizeTitleTranslation(track);
        String result = (String)JOptionPane.showInputDialog(
                this,
                "These translations were found",
                "Title translations",
                JOptionPane.PLAIN_MESSAGE,
                null,
                translations, translations[0]);

        if (result != null && result.length() > 0) t_artista.setText(result);
    }//GEN-LAST:event_b_translTitleActionPerformed

    private void b_transArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_transArtistActionPerformed
        if (tracks == null) return;
        MXMTrack track = tracks.get(pos);
        if (track == null) return;
        if (track.getArtistTranslations() == null ||
                track.getArtistTranslations().size() == 0) // la seconda parte del if non è necessaria, ma la metto per sicurezza
        {
            JOptionPane.showMessageDialog(this, "No translated artist name found.");
            return;
        }

        Object[] translations = References.normalizeArtistTranslation(track);
        String result = (String)JOptionPane.showInputDialog(
                this,
                "These translations were found",
                "Artist translations",
                JOptionPane.PLAIN_MESSAGE,
                null,
                translations, translations[0]);

        System.out.println(result); // TODO after checking things delete this statement

        if (result != null && result.length() > 0) t_titolo.setText(result);
    }//GEN-LAST:event_b_transArtistActionPerformed

    private void b_albCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_albCoverActionPerformed
        if (tracks == null) return;
        MXMTrack track = tracks.get(pos);
        if (track.getAlbumCover350x350() == null) {
            JOptionPane.showConfirmDialog(this, "No album cover found", "Album Coverart 350x350px", JOptionPane.PLAIN_MESSAGE);
            return;
        }

        ImageIcon im = new ImageIcon(track.getAlbumCover350x350());
        int result = JOptionPane.showConfirmDialog(
                this,
                "Do you really want to use this coverart instead of the tracks?",
                "Album Coverart 350x350px",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.PLAIN_MESSAGE,
                im
        );
        if (result == 0) l_cover.setIcon(im);
    }//GEN-LAST:event_b_albCoverActionPerformed

    private void l_logoMXMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_logoMXMMouseClicked
        String key = JOptionPane.showInputDialog(this, "Insert MusixMatch api key below:");

        References.MXM_API_KEY = key;
        System.out.println(References.MXM_API_KEY);
        MXM.updateMXM();
        References.writeConfigFile(
                key,
                References.LIB_DIR,
                References.FILTER_SEARCH
        );
    }//GEN-LAST:event_l_logoMXMMouseClicked

    private void b_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_searchActionPerformed
        jLabel2.setText("Start Scanning...");
        pos = 0;
        String[] aux = References.splitArrayForInput(t_input.getText());
        tracks = MXM.searchTrack(aux[0], aux[1]);

        jLabel2.setText("Search Terminated.");
        guiController( tracks.get(pos) );


    }//GEN-LAST:event_b_searchActionPerformed

    private void guiController(MXMTrack t)
    {
        if (t != null) {
            jLabel2.setText("Track found index: " + (pos + 1) + " of " + tracks.size() + " id: " + String
                    .valueOf(t.getTrackID()));

            t_titolo.setText(t.getTitle());
            t_artista.setText(t.getArtist());
            t_album.setText(t.getAlbum());
            t_anno.setText(t.getReleaseDate());
            t_numero.setText(String.valueOf(t.getTrackNumber()));
            cb_genere.setModel(new DefaultComboBoxModel<String>(References.normalizeTrackGenres(t)));


            if (t.getCoverart350x350() != null) {
                l_cover.setIcon(new ImageIcon(t.getCoverart350x350()));
            } else if (t.getCoverart100x100() != null) {
                // questo blocco else if è stato aggiunto in seguito, è da controllare, ma basicamente serve
                // a far si che trovi una cover 100px qualora non abbia una 350px
                l_cover.setIcon(new ImageIcon(t.getCoverart100x100()));
            } else {
                l_cover.setIcon(null);
                l_cover.setText("No Track Cover Found :(");
            }
        } else {
            jLabel2.setText("No track Seleceted/Found");
        }

    }

    private String[] setGeneriArray()
    {
        String[] unk = new String[] {"unknown"};
        if (tracks.get(pos).getGenres().size() ==  0) return unk;
        String[] rit = new String[tracks.get(pos).getGenres().size()];
        for (int i = 0; i < rit.length; i++) {
            rit[i] = tracks.get(pos).getGenres().get(i).getGenreName();
        }
        return rit;
    }

    public void setT_input(String input){t_input.setText(input);}

    public void setSong(Canzone s){song = s;}

    private int resultCount() {return tracks.size();}

    //private MXMTrack track;
    private List<MXMTrack> tracks;
    private int pos = 0;
    private Canzone                       song;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton           b_albCover;
    private javax.swing.JButton           b_match;
    private javax.swing.JButton           b_next;
    private javax.swing.JButton           b_prev;
    private javax.swing.JButton           b_save;
    private javax.swing.JButton           b_search;
    private javax.swing.JButton           b_transArtist;
    private javax.swing.JButton           b_translTitle;
    private javax.swing.JComboBox<String> cb_genere;
    private javax.swing.JLabel            jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_cover;
    private javax.swing.JTextField t_album;
    private javax.swing.JTextField t_anno;
    private javax.swing.JTextField t_artista;
    private javax.swing.JTextField t_input;
    private javax.swing.JTextField t_numero;
    private javax.swing.JTextField t_titolo;
    // End of variables declaration//GEN-END:variables
}
